return {
    Name = "Another Love",
    play = function(self, PianoPlayer)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.5625)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.5625)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.5625)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.5625)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.5625)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.5625)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.5625)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.5625)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.5625)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.5625)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.5625)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.75)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.75)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(1.5)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(1.5)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(1.5)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.9375)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.9375)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(1.875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(1.875)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
    end
}
