return {
    Name = "C418 - Mice on Venus",
    Category = "Minecraft",
    play = function(self, PianoPlayer)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(1.62162)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.54054)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(1.08108)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(1.08108)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(1.08108)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(1.08108)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(1.08108)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(1.08108)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(1.08108)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(1.08108)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(1.08108)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(1.08108)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(1.08108)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.81081)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.27027)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(1.08108)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.54054)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.54054)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(2.027025)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.067568)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.067567)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(1.08108)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(1.08108)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(1.08108)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(1.08108)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(1.62162)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.54054)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(1.08108)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(1.08108)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(2.16216)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("d", 0)
    end
}
