return {
    Name = "C418 - Wet Hands",
    play = function(self, PianoPlayer)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(1.216215)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(1.216215)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(1.62162)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.81081)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.81081)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(2.027025)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.050676)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.050676)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.304054)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.050676)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.760134)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.81081)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(1.216215)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.050676)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.050676)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.050676)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(2.280403)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.81081)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(1.62162)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(1.62162)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(1.216215)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.405405)
        PianoPlayer:playKey("P", 0)
    end
}
