return {
    Name = "C418 - Dry Hands (OST)",
    play = function(self, PianoPlayer)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.307812)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.8875)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(1.2125)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(1.792188)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.146875)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.1375)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.307812)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.14375)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(2.25)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.448437)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(3.171875)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.135938)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.295312)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.296875)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.459375)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(1.2)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.135937)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(0.448438)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(0.326562)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(0.279687)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(0.746875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.16875)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.451563)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.592187)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(2.854687)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.079687)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1125)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(1.009375)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(1.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(1.171875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(1.214063)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.065625)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(1.135938)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.59375)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.585938)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.0125)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.0625)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.0125)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(1.126563)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(1.189062)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.09375)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(0.214063)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.292187)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.615625)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.6)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.585938)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.015625)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.065625)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(1.121875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.0125)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(1.171875)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.015625)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.025)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(1.182812)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.603125)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:sleep(0.585938)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(1.204688)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:sleep(1.196875)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.065625)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:sleep(0.521875)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:sleep(1.196875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.592188)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.015625)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(0.59375)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:sleep(0.6)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.584375)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.59375)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:sleep(0.598437)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.603125)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(1.182812)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:sleep(0.589063)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(1.209375)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:sleep(0.603125)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.607812)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:sleep(1.178125)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.314062)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.279688)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.025)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.0625)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(0.520313)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.017187)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.279688)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.295312)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.914063)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.303125)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.582813)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(1.790625)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:sleep(0.017188)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.5875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(3.003125)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(0.079688)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.0625)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.0125)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(1.045313)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(1.19375)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(1.214063)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(1.185937)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.014063)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(2.4)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:sleep(0.215625)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.226563)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.145312)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.225)
        PianoPlayer:playKey("H", 0)
    end
}
