return {
    Name = "Pirates of the Caribbean - He's a Pirate",
    play = function(self, PianoPlayer)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("4", 0)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("4", 0)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("4", 0)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.075)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.075)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("%", 0)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("%", 0)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("%", 0)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("%", 0)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("(", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("W", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.3)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.45)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.15)
        PianoPlayer:playKey("4", 0)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("f", 0)
    end
}
