return {
    Name = "du bist gut genug",
    play = function(self, PianoPlayer)
        PianoPlayer:sleep(1.183594)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.080729)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.442708)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.533854)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.501302)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.045573)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.325521)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(1.522135)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.140625)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.348958)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.789063)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.25651)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.488281)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.859375)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.486979)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.488281)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.535156)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.509115)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.291667)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.033854)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.441406)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.268229)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.25651)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(2.809896)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.417969)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.247396)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.302083)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.440104)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.476563)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.279948)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.498698)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.47526)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.523438)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.023438)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.221354)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.279948)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.045573)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.429688)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.513021)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.234375)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.369792)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(1.152344)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.234375)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.324219)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.466146)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.476563)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.266927)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(1.498698)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.279948)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.25651)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.070313)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.046875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.394531)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.092448)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.394531)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.023438)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.477865)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.313802)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.25651)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.661458)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.208333)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.407552)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.023438)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.486979)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.513021)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.407552)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.058594)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.092448)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.221354)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.291667)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.266927)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.291667)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.022135)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.139323)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.265625)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.186198)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.523438)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.114583)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.592448)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.231771)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.486979)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.046875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.104167)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.372396)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.335938)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.140625)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.022135)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.220052)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.25651)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.06901)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.441406)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.498698)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.105469)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.117188)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.022135)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.25651)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.208333)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.300781)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.268229)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.220052)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.023438)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.231771)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.266927)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.268229)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.046875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.220052)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(2.220052)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.221354)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.268229)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.385417)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.151042)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.266927)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.092448)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.429688)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.06901)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.16276)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.253906)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.384115)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.591146)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.395833)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.197917)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.186198)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.023438)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.070313)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.463542)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.09375)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.395833)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.535156)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.266927)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.361979)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.022135)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.278646)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.106771)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.604167)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.151042)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.558594)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.441406)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.231771)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.277344)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.513021)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.511719)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.384115)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.139323)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.25651)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.498698)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.476563)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.488281)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.278646)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.126302)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.361979)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.105469)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.382813)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.265625)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:sleep(0.231771)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.046875)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.151042)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.02474)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.265625)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.09375)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.022135)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:sleep(0.384115)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.105469)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.127604)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.25651)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:sleep(0.231771)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.488281)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.035156)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.454427)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.184896)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:sleep(0.035156)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.174479)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.070313)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.197917)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.209635)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.022135)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.279948)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.186198)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.092448)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.186198)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.221354)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.022135)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.498698)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.234375)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.046875)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:sleep(0.195313)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.25651)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.022135)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.221354)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.023438)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.080729)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.16276)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.209635)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.25651)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.359375)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.127604)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.269531)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.486979)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:sleep(0.080729)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.173177)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.080729)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.127604)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.070313)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.035156)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:sleep(0.184896)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.023438)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.209635)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.023438)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.222656)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.022135)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.070313)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.115885)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.265625)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.035156)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.231771)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.266927)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.234375)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.278646)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.231771)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.080729)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:sleep(0.151042)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.023438)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.231771)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.498698)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.35026)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.127604)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.046875)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.105469)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.035156)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.140625)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.221354)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.186198)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.035156)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:sleep(0.022135)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.231771)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.488281)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.266927)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.25651)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.231771)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.266927)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.035156)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.453125)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.092448)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:sleep(0.384115)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.080729)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.139323)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.046875)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.035156)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.140625)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.080729)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.117188)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.080729)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.080729)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:sleep(0.164063)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.022135)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.196615)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.209635)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.06901)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.197917)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.023438)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.046875)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.268229)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:sleep(0.151042)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.16276)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.348958)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.210938)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.035156)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.057292)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.16276)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.105469)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.384115)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.231771)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.266927)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:sleep(0.208333)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.231771)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.220052)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.279948)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.347656)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.057292)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.046875)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.023438)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.070313)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.16276)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:sleep(0.105469)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.268229)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.114583)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.046875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.429688)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.09375)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.092448)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.175781)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.080729)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:sleep(0.407552)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.25651)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.221354)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.290365)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.048177)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.208333)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:sleep(0.092448)
        PianoPlayer:playKey("\"", 0)
        PianoPlayer:sleep(0.40625)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.023438)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:sleep(0.115885)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.326823)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.152344)
        PianoPlayer:playKey("\"", 0)
        PianoPlayer:sleep(0.33724)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:sleep(0.186198)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.035156)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.511719)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.278646)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:sleep(0.21224)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.080729)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:sleep(0.186198)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.208333)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.022135)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.209635)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.035156)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.046875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:sleep(0.313802)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.347656)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.079427)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:sleep(0.070313)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.35026)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.057292)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.186198)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:sleep(0.057292)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.023438)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.346354)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.464844)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.117188)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.104167)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.210938)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.045573)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.046875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.253906)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.023438)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.395833)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.173177)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.046875)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.246094)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.070313)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.140625)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:sleep(0.266927)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.231771)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.022135)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.023438)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:sleep(0.220052)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.197917)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.522135)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.070313)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.152344)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.208333)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.266927)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.115885)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:sleep(0.348958)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.080729)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.046875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:sleep(0.151042)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.197917)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.070313)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.138021)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.023438)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.25651)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.05599)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:sleep(0.395833)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.080729)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.080729)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:sleep(0.328125)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.47526)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.105469)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.059896)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:sleep(0.21875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.106771)
        PianoPlayer:playKey(")", 0)
        PianoPlayer:sleep(0.335938)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.453125)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.022135)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.070313)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.16276)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.035156)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.080729)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.395833)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.023438)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:sleep(0.208333)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.338542)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.372396)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.231771)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.057292)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.070313)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.419271)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.511719)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.117188)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.559896)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.070313)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.115885)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.348958)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.290365)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.442708)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.022135)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.080729)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.161458)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(1.197917)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.265625)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.117188)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.138021)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.233073)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.013021)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.105469)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:sleep(0.347656)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.173177)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.404948)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.246094)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.115885)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:sleep(0.38151)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:sleep(0.59375)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.488281)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.33724)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.231771)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.557292)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.140625)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.011719)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.140625)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(3.05599)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.080729)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.057292)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:sleep(0.046875)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.022135)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:sleep(0.046875)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(1.986979)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.627604)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.24349)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.114583)
        PianoPlayer:playKey("a", 0)
    end
}
