return {
    Name = "Für Elise",
    play = function(self, PianoPlayer)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:sleep(0.083984)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.103516)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.5625)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.5625)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(1.125)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.5625)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.5625)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Q", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Q", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Q", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Q", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Q", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Q", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(1.125)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(1.125)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.125)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.125)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.126953)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.126953)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.125)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.126953)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.126953)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.125)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.126953)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.126953)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.125)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.126953)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.378906)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.378906)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.757813)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.378906)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(1.515625)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.126953)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.125)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.126953)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.126953)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.125)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.126953)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.375)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.1875)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("k", 0)
    end
}
