return {
    Name = "Grow A Garden - Main Theme",
    Category = "Games",
    play = function(self, PianoPlayer)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.170454)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.272727)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.136363)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.238636)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("0", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(1.227271)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.170454)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.272727)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.136363)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.238636)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("0", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("7", 0)
        PianoPlayer:playKey("Q", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(1.499999)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.818181)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.818181)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.818181)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(1.227272)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(1.227272)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.818181)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(1.227272)
        PianoPlayer:playKey("7", 0)
        PianoPlayer:playKey("Q", 0)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("7", 0)
        PianoPlayer:playKey("Q", 0)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.136364)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.272727)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.136364)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.272727)
        PianoPlayer:playKey("7", 0)
        PianoPlayer:playKey("Q", 0)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("0", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(1.636362)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.409091)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.40909)
        PianoPlayer:playKey("S", 0)
    end
}
