return {
    Name = "Minecraft -  Sweden",
    Category = "Minecraft",
    play = function(self, PianoPlayer)
        PianoPlayer:sleep(0.97826)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(1.331521)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(1.29076)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(1.294157)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(1.294157)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(1.338314)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(1.29076)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(2.588314)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(1.338314)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(1.29076)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(1.294157)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(1.294157)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(1.338314)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(1.29076)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(2.588314)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(1.338314)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(1.29076)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(1.294157)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(1.294157)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(1.338314)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(1.29076)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(2.588314)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(1.338314)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.648777)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(1.294157)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.326087)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.319293)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(1.331521)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.315897)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.33288)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(2.588314)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.658967)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.652174)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.027174)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(0.625)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.652174)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.013587)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(1.294157)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.326087)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.319293)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(1.331521)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.625)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.326087)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.326087)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.013587)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(2.588314)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(1.31114)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.027174)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(0.625)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.652174)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.013587)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(1.294157)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.309103)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.016984)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.319293)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(1.331521)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.625)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.016984)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.309103)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.326087)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.013587)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(2.588314)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(1.338314)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.648777)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(1.294157)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.315897)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.336277)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(1.338314)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.315897)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.33288)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(2.588314)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(1.331521)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.63519)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.013587)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(1.294157)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.315897)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.336277)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(1.331521)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.315897)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.319293)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(2.59171)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.02038)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:sleep(1.304347)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.65557)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.648777)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(1.304347)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.631793)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.02038)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.295516)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.336277)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.02038)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(1.304347)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.013587)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.315897)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.33288)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(2.59171)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.013587)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:sleep(1.959917)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.315897)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.319293)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:sleep(0.013587)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(1.294157)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.652174)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.01)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:sleep(1.966711)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.315897)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.33288)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.013587)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:sleep(2.574727)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.013587)
        PianoPlayer:playKey("9", 0)
        PianoPlayer:sleep(1.966711)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.315897)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.33288)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(1.294157)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.652174)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.013587)
        PianoPlayer:playKey("8", 0)
        PianoPlayer:sleep(1.324727)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.315897)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.319293)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.013587)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.013587)
        PianoPlayer:playKey("&", 0)
        PianoPlayer:sleep(4.548231)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(1.304347)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(1.28057)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.023777)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.02038)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.013587)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.013587)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.244565)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(1.015624)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.652174)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.326087)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.159647)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.16644)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.3125)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.991847)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.679347)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.326087)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.298913)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(2.608694)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(1.304347)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.027174)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(1.086956)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.190217)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.125679)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(1.178668)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.652174)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.326087)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.159647)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.16644)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.149456)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(1.199048)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.608016)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.305706)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.346467)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(2.608694)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.689538)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.648777)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.648777)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(1.294157)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.315897)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.336277)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(1.338314)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.315897)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.33288)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(2.588314)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(1.338314)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.648777)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.648777)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.64538)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.315897)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.336277)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(1.338314)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.315897)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.33288)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(2.588314)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.689538)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.648777)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.648777)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.648777)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.64538)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("V", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.315897)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.336277)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(1.338314)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.315897)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.33288)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(2.588314)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(1.338314)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(1.29076)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(1.294157)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.652173)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(1.338314)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(1.29076)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(2.588314)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(1.338314)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(1.29076)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(1.294157)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.641983)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.652174)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(1.338314)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(1.29076)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(2.588314)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(1.338314)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(1.29076)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(1.294157)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(1.294157)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(1.338314)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(1.29076)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("G", 0)
    end
}
