return {
    Name = "It's Raining Tacos!",
    play = function(self, PianoPlayer)
        PianoPlayer:sleep(1.714284)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.428571)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.428571)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.428571)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.428571)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.428571)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.160714)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.053571)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.160714)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.053571)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("Q", 0)
        PianoPlayer:playKey("Q", 0)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("Q", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("Q", 0)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("Q", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("Q", 0)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.107143)
        PianoPlayer:playKey("Q", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("Q", 0)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("Q", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(2.142855)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.428571)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.428571)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.857142)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.428571)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.428571)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(1.071428)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.428571)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.428571)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(1.071427)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.428571)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.428571)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("b", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("c", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.428571)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.428571)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("o", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.428571)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.428571)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("m", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("v", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:playKey("f", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("q", 0)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("Y", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("d", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("E", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("p", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("z", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("g", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("r", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:playKey("h", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("T", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.214285)
        PianoPlayer:playKey("s", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:playKey("l", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("i", 0)
        PianoPlayer:sleep(0.214286)
        PianoPlayer:playKey("j", 0)
        PianoPlayer:playKey("j", 0)
    end
}
