return {
    Name = "River Flows In You",
    play = function(self, PianoPlayer)
        PianoPlayer:sleep(0.010417)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.523438)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(4)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(4)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.257812)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.25)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.085938)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.442708)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.736979)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.125)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.130208)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.25)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.088542)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.440104)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.283854)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.283854)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.236979)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.283854)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.221354)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.015625)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.236979)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.236979)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.283854)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.221354)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.015625)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(4)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.25)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.088542)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.440104)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.25)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.283854)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.5)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.088542)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.440104)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.25)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.088542)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.440104)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.25)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.283854)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.283854)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.221354)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.015625)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.236979)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.236979)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.283854)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.221354)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.015625)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.236979)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.257812)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.236979)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.283854)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.236979)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:sleep(0.236979)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.283854)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.244792)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.221354)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.015625)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.239583)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.252604)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.236979)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.333333)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.083333)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.085938)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.5)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.992188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.333333)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.083333)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(0.085938)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:sleep(0.5)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.736979)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.125)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.130208)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.333333)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.083333)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.083333)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("n", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.5)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:sleep(0.088542)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.440104)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.989583)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("S", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:playKey("B", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("U", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("G", 0)
        PianoPlayer:playKey("k", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.257813)
        PianoPlayer:playKey("t", 0)
        PianoPlayer:playKey("C", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("I", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("x", 0)
        PianoPlayer:sleep(0.242188)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.255208)
        PianoPlayer:playKey("w", 0)
        PianoPlayer:playKey("L", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("y", 0)
        PianoPlayer:sleep(0.494792)
        PianoPlayer:playKey("P", 0)
        PianoPlayer:playKey("J", 0)
        PianoPlayer:sleep(0.992188)
        PianoPlayer:playKey("e", 0)
        PianoPlayer:playKey("Z", 0)
        PianoPlayer:sleep(0.528646)
        PianoPlayer:playKey("u", 0)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:sleep(0.497396)
        PianoPlayer:playKey("O", 0)
        PianoPlayer:playKey("D", 0)
        PianoPlayer:sleep(0.492188)
        PianoPlayer:playKey("H", 0)
        PianoPlayer:sleep(1.489583)
        PianoPlayer:playKey("a", 0)
        PianoPlayer:playKey("k", 0)
    end
}
